config/routes.rb
Zoomin::Application.routes.draw do
  get :matcher, :to => "zooms#matcher"
  get :activate, :to => "positions#setactive"
  get :deactivate, :to => "positions#setunactive"
  get :inbox,:to => "users#inbox"
  get :allactive, :to => "positions#allactive"

  resources :zoomins


  resources :positions


  resources :profiles
  get :getprofile, :to => "profiles#getprofile"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :company_name, :company_position, :description, :status, :user_id
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  require 'rest_client'

  # GET /profiles
  # GET /profiles.json
  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  # For all responses in this controller, return the CORS access control headers.
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.

  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
    headers['Access-Control-Max-Age'] = '1728000'
  end


  def index
    @profile = User.find(params[:user_id]).profile
    @profiles = Profile.where("id != ?",@profile.id)
    respond_to do |format|
      format.json { render :json => @profiles, :callback => params['callback'] }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find_by_email(params[:email])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile, :callback => params['callback'] }
    end
  rescue
    @profile = Profile.find(1)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def getprofile
    @profile = User.find_by_email(params[:email]).profile
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile, :callback => params['callback'] }
    end
  rescue
    @profile = User.find(1).profile
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile, :callback => params['callback'] }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])
    @response = RestClient.get 'https://api.pearson.com/v2/dictionaries/entries', {:accept =>:json,
                                                                                   :params => {'api_key' => 'agG6dPfed6A8bXuQybq2GGAm2fPVpE'}}
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company_name %>
    <%= f.input :company_position %>
    <%= f.input :description %>
    <%= f.input :user_id %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Company name</th>
    <th>Company position</th>
    <th>Description</th>
    <th>User</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.company_name %></td>
    <td><%= profile.company_position %></td>
    <td><%= profile.description %></td>
    <td><%= profile.user_id %></td>
    <td><%= profile.status %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company name:</b>
  <%= @profile.company_name %>
</p>

<p>
  <b>Company position:</b>
  <%= @profile.company_position %>
</p>

<p>
  <b>Description:</b>
  <%= @profile.description %>
</p>

<p>
  <b>User:</b>
  <%= @profile.user_id %>
</p>

<p>
  <b>Status:</b>
  <%= @profile.status %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>