config/routes.rb
Zoomin::Application.routes.draw do
  get :matcher, :to => "zooms#matcher"
  get :activate, :to => "positions#setactive"
  get :deactivate, :to => "positions#setunactive"
  get :inbox,:to => "users#inbox"
  get :allactive, :to => "positions#allactive"

  resources :zoomins


  resources :positions


  resources :profiles
  get :getprofile, :to => "profiles#getprofile"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :lat, :long, :radio, :user_id
  belongs_to :user
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  # GET /positions
  # GET /positions.json
  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  # For all responses in this controller, return the CORS access control headers.
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.

  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
    headers['Access-Control-Max-Age'] = '1728000'
  end



  # POST /positions
  # POST /positions.json
  def setactive
    @user = User.find(params[:user_id])
    @user.position.lat =params[:lat]
    @user.position.long =params[:long]
    @user.position.radio =params[:rad]
    @user.position.status = "online"

    respond_to do |format|
      if @user.save
        format.json { render json: @user.position, :callback => params['callback'] }
      else
        format.json { render json: @user.position.errors, status: :unprocessable_entity , :callback => params['callback']}
      end
    end
  end

  def allactive
    respond_to do |format|
        format.json { render json: Position.where(:status => "online"), :callback => params['callback'] }
    end
  end

  def setunactive
    @user = User.find(params[:user_id])
    @user.position.status = "offline"

    respond_to do |format|
      if @user.save
        format.json { render json: @user.position, status: :created, location: @position, :callback => params['callback'] }
      else
        format.json { render json: @user.position.errors, status: :unprocessable_entity, :callback => params['callback'] }
      end
    end
  end


  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end


  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= simple_form_for(@position) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :lat %>
    <%= f.input :long %>
    <%= f.input :radio %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <tr>
    <th>Lat</th>
    <th>Long</th>
    <th>Radio</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.lat %></td>
    <td><%= position.long %></td>
    <td><%= position.radio %></td>
    <td><%= position.user_id %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lat:</b>
  <%= @position.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @position.long %>
</p>

<p>
  <b>Radio:</b>
  <%= @position.radio %>
</p>

<p>
  <b>User:</b>
  <%= @position.user_id %>
</p>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>