config/routes.rb
Zoomin::Application.routes.draw do
  get :matcher, :to => "zooms#matcher"
  get :activate, :to => "positions#setactive"
  get :deactivate, :to => "positions#setunactive"
  get :inbox,:to => "users#inbox"
  get :allactive, :to => "positions#allactive"

  resources :zoomins


  resources :positions


  resources :profiles
  get :getprofile, :to => "profiles#getprofile"
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/zoom.rb
class Zoom < ActiveRecord::Base
  attr_accessible :first_meeter_id, :second_meeter_id, :status
  belongs_to :first_meeter, :class_name => 'User', :foreign_key => 'first_meeter_id'
  belongs_to :second_meeter, :class_name => 'User', :foreign_key => 'second_meeter_id'

end

app/controllers/zooms_controller.rb
class ZoomsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  # For all responses in this controller, return the CORS access control headers.
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.

  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
    headers['Access-Control-Max-Age'] = '1728000'
  end


  def index
    @zooms = Zoom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zooms }
    end
  end


  # POST /zoomins
  # POST /zoomins.json
  def matcher
    #from_user_id to_user_id
    @zoom = Zoom.where("(first_meeter_id == ? or second_meeter_id == ?) and status == ?", params[:user_id], params[:user_id], "matched")
    if !@zoom.empty?
      respond_to do |format|
        if @zoom.update_attributes(:status => "matched")
          AdminMailer.new_match(params[:to_user_id],params[:from_user_id]) 

          format.json { render json: {match: true}, :callback => params['callback'] }
        else
          format.json { render json: {match: false}, :callback => params['callback'] }
        end
      end
      #cambia estado a matched
    else
      #añades un posible match
      @zoom = Zoom.new(:first_meeter_id => params[:from_user_id], :second_meeter_id => params[:to_user_id], :status => "waiting")
      respond_to do |format|
        if @zoom.save
          format.json { render json: {match: false}, :callback => params['callback'] }
        else
          format.json { render json: {match: false}, :callback => params['callback'] }
        end
      end
    end
  end

end

app/views/zooms/_form.html.erb
<%= simple_form_for(@zoomin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_meeter_id %>
    <%= f.input :second_meeter_id %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/zooms/edit.html.erb
<h1>Editing zoomin</h1>

<%= render 'form' %>

<%= link_to 'Show', @zoomin %> |
<%= link_to 'Back', zoomins_path %>

app/views/zooms/index.html.erb
<h1>Listing zoomins</h1>

<table>
  <tr>
    <th>First meeter</th>
    <th>Second meeter</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zoomins.each do |zoomin| %>
  <tr>
    <td><%= zoomin.first_meeter_id %></td>
    <td><%= zoomin.second_meeter_id %></td>
    <td><%= zoomin.status %></td>
    <td><%= link_to 'Show', zoomin %></td>
    <td><%= link_to 'Edit', edit_zoomin_path(zoomin) %></td>
    <td><%= link_to 'Destroy', zoomin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zoomin', new_zoomin_path %>

app/views/zooms/new.html.erb
<h1>New zoomin</h1>

<%= render 'form' %>

<%= link_to 'Back', zoomins_path %>

app/views/zooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First meeter:</b>
  <%= @zoomin.first_meeter_id %>
</p>

<p>
  <b>Second meeter:</b>
  <%= @zoomin.second_meeter_id %>
</p>

<p>
  <b>Status:</b>
  <%= @zoomin.status %>
</p>


<%= link_to 'Edit', edit_zoomin_path(@zoomin) %> |
<%= link_to 'Back', zoomins_path %>